scope:\ addon api:
  - addons/**

scope:\ ci:
  - .github/workflows/*

scope:\ extension workings:
  - background/**
  - content-scripts/**

scope:\ l10n:
  - _locales/**
  - addons-l10n/**

scope:\ webpages: 
  - addons/**

scope:\ meta:
  - ".github/**"
  - "!.github/workflows/*"
  - "*"
  - "!*/**"
