//Every emoji in the picker

//imager2 is required for better-emojis to work in the picker
export const emojis = [
  {
    text: "_meow_",
    image: "/images/emoji/meow.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/meow.png",
  },
  {
    text: "_gobo_",
    image: "/images/emoji/gobo.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/gobo.png",
  },
  {
    text: "_:)_",
    image: "/images/emoji/cat.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/cat.png",
  },
  {
    text: "_:D_",
    image: "/images/emoji/aww-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/aww-cat.png",
  },
  {
    text: "_B)_",
    image: "/images/emoji/cool-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/cool-cat.png",
  },
  {
    text: "_:P_",
    image: "/images/emoji/tongue-out-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/tongue-out-cat.png",
  },
  {
    text: "_;P_",
    image: "/images/emoji/wink-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/wink-cat.png",
  },
  {
    text: "_:'P_",
    image: "/images/emoji/lol-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/lol-cat.png",
  },
  {
    text: "_P:_",
    image: "/images/emoji/upside-down-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/upside-down-cat.png",
  },
  {
    text: "_:3_",
    image: "/images/emoji/huh-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/huh-cat.png",
  },
  {
    text: "_<3_",
    image: "/images/emoji/love-it-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/love-it-cat.png",
  },
  {
    text: "_**_",
    image: "/images/emoji/fav-it-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/fav-it-cat.png",
  },
  {
    text: "_:))_",
    image: "/images/emoji/rainbow-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/rainbow-cat.png",
  },
  {
    text: "_:D<_",
    image: "/images/emoji/pizza-cat.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/pizza-cat.png",
  },
  {
    text: "_10mil_",
    image: "/images/emoji/10mil.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/10mil.png",
  },
  {
    text: "_waffle_",
    image: "/images/emoji/waffle.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/waffle.png",
  },
  {
    text: "_taco_",
    image: "/images/emoji/taco.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/taco.png",
  },
  {
    text: "_sushi_",
    image: "/images/emoji/sushi.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/sushi.png",
  },
  {
    text: "_apple_",
    image: "/images/emoji/apple.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/apple.png",
  },
  {
    text: "_broccoli_",
    image: "/images/emoji/broccoli.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/broccoli.png",
  },
  {
    text: "_pizza_",
    image: "/images/emoji/pizza.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/pizza.png",
  },
  {
    text: "_candycorn_",
    image: "/images/emoji/candycorn.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/candycorn.png",
  },
  {
    text: "_map_",
    image: "/images/emoji/map.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/map.png",
  },
  {
    text: "_camera_",
    image: "/images/emoji/camera.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/camera.png",
  },
  {
    text: "_suitcase_",
    image: "/images/emoji/suitcase.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/suitcase.png",
  },
  {
    text: "_compass_",
    image: "/images/emoji/compass.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/compass.png",
  },
  {
    text: "_binoculars_",
    image: "/images/emoji/binoculars.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/binoculars.png",
  },
  {
    text: "_cupcake_",
    image: "/images/emoji/cupcake.png",
    imager2:
      "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/cupcake.png",
  },
  {
    text: "_pride_",
    image: "/images/emoji/pride.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/pride.png",
  },
  {
    text: "_blm_",
    image: "/images/emoji/blm.png",
    imager2: "//cdn.scratch.mit.edu/scratchr2/static/__9e4044de46c7852aec750b6571cceb92__/images/easter_eggs/blm.png",
  },
];
//Scratch only supports Unicode emojis inside the Basic Multilingual Plane.
//This array contains all of those emojis.
//"br" is automatically converted to a section break.
export const unicodeEmojis = [
  "⌚️",
  "⏰",
  "⏱️",
  "⏲️",
  "⌨️",
  "☎️",
  "⌛️",
  "⚖️",
  "⚙️",
  "✉️",
  "✂️",
  "✒️",
  "☂️",
  "✏️",
  "☕️",
  "♟️",
  "⚰️",
  "⚱️",
  "⛏️",
  "⚔️",
  "⚒️",
  "⛓️",
  "⚗️",
  "⛑️",
  "br",
  "⭐️",
  "✨",
  "⚡️",
  "☄️",
  "☀️",
  "⛅️",
  "☁️",
  "⛈️",
  "⛄️",
  "❄️",
  "☔️",
  "☘️",
  "br",
  "☹️",
  "✌️",
  "☝️",
  "✍️",
  "✋",
  "☺️",
  "br",
  "⚽️",
  "⚾️",
  "⛳️",
  "⛹️",
  "⛷️",
  "⛸️",
  "br",
  "✈️",
  "⛵️",
  "Ⓜ️",
  "⚓️",
  "⛽️",
  "⛲️",
  "⛺️",
  "⛪️",
  "⛰️",
  "⛱️",
  "⛴️",
  "⛩️",
  "♨️",
  "br",
  "❗️",
  "❕",
  "❓",
  "❔",
  "©️",
  "®️",
  "‼️",
  "⁉️",
  "™️",
  "➕",
  "➖",
  "➗",
  "✖️",
  "⛔",
  "⭕",
  "❌",
  "✔️",
  "〰️",
  "〽️",
  "⚠️",
  "br",
  "☑️",
  "✅",
  "❎",
  "▶️",
  "⏩",
  "⏪",
  "⏫",
  "⏬",
  "ℹ️",
  "⏭️",
  "⏮️",
  "⏯️",
  "⏏️",
  "◀️",
  "➡️",
  "⬅️",
  "⬆️",
  "⬇️",
  "↗️",
  "↘️",
  "↙️",
  "↖️",
  "↪️",
  "↩️",
  "⤴️",
  "⤵️",
  "✳️",
  "✴️",
  "❇️",
  "㊗️",
  "㊙️",
  "br",
  "⚕️",
  "☦️",
  "♾️",
  "⚛️",
  "⛎️",
  "✝️",
  "☪️",
  "☮️",
  "☯️",
  "☸️",
  "♈️",
  "♉️",
  "♊️",
  "♋️",
  "♌️",
  "♍️",
  "♎️",
  "♏️",
  "♐️",
  "♑️",
  "♒️",
  "♓️",
  "br",
  "❤️",
  "❣️",
  "♠️",
  "♣️",
  "♥️",
  "♦️",
  "♀️",
  "♂️",
  "♻️",
  "☢️",
  "☣️",
  "⚜️",
  "➰️",
  "➿️",
  "☠️",
  "br",
  "⬛️",
  "⬜️",
  "⚪️",
  "⚫️",
  "▪️",
  "▫️",
  "◻️",
  "◼️",
  "◽️",
  "◾️",
];
