name: 🐛 Bug
description: Report a bug.
labels: ["status: needs triage", "type: bug"]
body:
  - type: markdown
    attributes:
      value: | 
        ### Read before creating!

        - Avoid creating duplicates! Read the FAQ page and search through issues and discussions before creating one.
        - Try to make a simple but descriptive title, and include the detailed information below. This could save a lot of time and help us fix issues swiftly.
        - Make sure to use the latest version of Scratch Addons.
        - For help, check our [FAQ page](https://scratchaddons.com/faq), open a [discussion](https://github.com/ScratchAddons/ScratchAddons/discussions) or ask on our [Discord server](https://discord.gg/R5NBqwMjNc).
        - If you found a security vulnerability, please read our [security policy](https://github.com/ScratchAddons/ScratchAddons/security/policy).

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include a clear and concise description of what should happen and what's actually happening.
      placeholder: I can't see the button...
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Provide an unambiguous set of steps to reproduce this bug.
      placeholder: |
        1. Open a Scratch project.
        2. Click See inside.
        3. Open the costume editor.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: additonalcontext
    attributes:
      label: Demonstration(s) and additional context
      description: If applicable, insert screenshots or a live example to help demonstrate your problem, as well as any other useful infomation here.

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include information related to your environment/device.
      placeholder: Include what version of Scratch Addons you're using (can be found in the extension popup), your browser and its version, and your operating system.
      value: |
        Browser: <!-- e.g. Chrome 89 -->
        Scratch Addons version: <!-- e.g. 1.10.0. For pre-releases, include hash if possible -->
        Operating system: <!-- e.g. Windows -->
    validations:
      required: true
