name: ➕ New addon
description: Suggest a new addon!
labels: ["new addon", "scope: addon", "type: enhancement"]
body:
  - type: markdown
    attributes:
      value: | 
        ### Read before creating!

        - Avoid creating duplicates! Read the FAQ page and search through issues and discussions before creating one.
        - Try to make a simple but descriptive title, and include the detailed information below.
        - Make sure to use the latest version of Scratch Addons.
        - For help, check our [FAQ page](https://scratchaddons.com/faq), open a [discussion](https://github.com/ScratchAddons/ScratchAddons/discussions) or ask on our [Discord server](https://discord.gg/R5NBqwMjNc).

  - type: textarea
    id: problem
    attributes:
      label: Why this would be helpful
      description: How would this help with a problem or make something better?
      placeholder: Sometimes I want to...
    validations:
      required: true

  - type: textarea
    id: howitworks
    attributes:
      label: How this addon works
      description: Describe your addon and how it works.
      placeholder: This addon adds a button to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Possible alternatives
      description: Any alternative solutions or features you've thought about?
      placeholder: We could also ... instead.

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Add any other information like screenshots, videos, or context about your new addon here.
