export default {
  "meow.png": "[meow emoji]",
  "gobo.png": "[gobo emoji]",
  "waffle.png": "[waffle emoji]",
  "taco.png": "🌮",
  "sushi.png": "🍣",
  "apple.png": "🍎",
  "broccoli.png": "🥦",
  "pizza.png": "🍕",
  "candycorn.png": "[candycorn emoji]",
  "10mil.png": "🎉",
  "map.png": "🗺️",
  "camera.png": "📷",
  "suitcase.png": "💼",
  "compass.png": "🧭",
  "binoculars.png": "[binoculars emoji]",
  "cupcake.png": "🧁",
  "cat.png": "🐱",
  "aww-cat.png": "😀",
  "cool-cat.png": "😎",
  "tongue-out-cat.png": "😛",
  "wink-cat.png": "😜",
  "lol-cat.png": "😹",
  "upside-down-cat.png": "🙃",
  "huh-cat.png": "🤨",
  "love-it-cat.png": "😻",
  "fav-it-cat.png": "🤩",
  "rainbow-cat.png": "[rainbow cat emoji]",
  "pizza-cat.png": "[cat eating pizza emoji]",
};
