export default {
  "d(?-2P98l-aDw*wD;E^@": {
    opcode: "procedures_definition",
    next: "QaHY6^_#(U|w?u9`O}+7",
    parent: null,
    inputs: {
      custom_block: [1, "G}%%%Z)`lLeEo=p:Rk{d"],
    },
    fields: {},
    shadow: false,
    topLevel: true,
    x: 0,
    y: 0,
  },
  "G}%%%Z)`lLeEo=p:Rk{d": {
    opcode: "procedures_prototype",
    next: null,
    parent: "d(?-2P98l-aDw*wD;E^@",
    inputs: {
      "4PK./iHHj:gdrSiUlMi2": [1, "S:=e3ATAiYg4u|Itl^Pf"],
    },
    fields: {},
    shadow: true,
    topLevel: false,
    mutation: {
      tagName: "mutation",
      children: [],
      proccode: "Display %s",
      argumentids: '["4PK./iHHj:gdrSiUlMi2"]',
      argumentnames: '["text"]',
      argumentdefaults: '[""]',
      warp: "true",
    },
  },
  "S:=e3ATAiYg4u|Itl^Pf": {
    opcode: "argument_reporter_string_number",
    next: null,
    parent: "G}%%%Z)`lLeEo=p:Rk{d",
    inputs: {},
    fields: {
      VALUE: ["text", null],
    },
    shadow: true,
    topLevel: false,
  },
  "QaHY6^_#(U|w?u9`O}+7": {
    opcode: "looks_show",
    next: "JxcJjvVwWov1`p?G@/+l",
    parent: "d(?-2P98l-aDw*wD;E^@",
    inputs: {},
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "JxcJjvVwWov1`p?G@/+l": {
    opcode: "data_setvariableto",
    next: "=VO(cpH(vlYoit^~[zV)",
    parent: "QaHY6^_#(U|w?u9`O}+7",
    inputs: {
      VALUE: [1, [10, "1"]],
    },
    fields: {
      VARIABLE: ["i", "display_index"],
    },
    shadow: false,
    topLevel: false,
  },
  "=VO(cpH(vlYoit^~[zV)": {
    opcode: "control_repeat_until",
    next: "g7i[~Ts%_4+[a[qF6Xm[",
    parent: "JxcJjvVwWov1`p?G@/+l",
    inputs: {
      CONDITION: [2, "TNQZ}8,Vd3Wkc?{W3C0~"],
      SUBSTACK: [2, "|}#t;snIZ/StTVPDkol+"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "TNQZ}8,Vd3Wkc?{W3C0~": {
    opcode: "operator_gt",
    next: null,
    parent: "=VO(cpH(vlYoit^~[zV)",
    inputs: {
      OPERAND1: [3, [12, "i", "display_index"], [10, ""]],
      OPERAND2: [3, "p2E+7]dIx5d{k2Ql+5VY", [10, "50"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "p2E+7]dIx5d{k2Ql+5VY": {
    opcode: "operator_length",
    next: null,
    parent: "TNQZ}8,Vd3Wkc?{W3C0~",
    inputs: {
      STRING: [3, "Z3xo70Gj^_xetPz?vpst", [10, "apple"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "Z3xo70Gj^_xetPz?vpst": {
    opcode: "argument_reporter_string_number",
    next: null,
    parent: "p2E+7]dIx5d{k2Ql+5VY",
    inputs: {},
    fields: {
      VALUE: ["text", null],
    },
    shadow: false,
    topLevel: false,
  },
  "|}#t;snIZ/StTVPDkol+": {
    opcode: "looks_switchcostumeto",
    next: "fVmso.joua4IgCvob-yY",
    parent: "=VO(cpH(vlYoit^~[zV)",
    inputs: {
      COSTUME: [3, "#J@7*o7ZXcBsz=@@I6fg", "spjmEue^SG48kwWTeZN5"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "#J@7*o7ZXcBsz=@@I6fg": {
    opcode: "operator_letter_of",
    next: null,
    parent: "|}#t;snIZ/StTVPDkol+",
    inputs: {
      LETTER: [3, [12, "i", "display_index"], [6, "1"]],
      STRING: [3, "d:-JwDQJw_]DpF6q]j*g", [10, "apple"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "d:-JwDQJw_]DpF6q]j*g": {
    opcode: "argument_reporter_string_number",
    next: null,
    parent: "#J@7*o7ZXcBsz=@@I6fg",
    inputs: {},
    fields: {
      VALUE: ["text", null],
    },
    shadow: false,
    topLevel: false,
  },
  "spjmEue^SG48kwWTeZN5": {
    opcode: "looks_costume",
    next: null,
    parent: "|}#t;snIZ/StTVPDkol+",
    inputs: {},
    fields: {
      COSTUME: ["—", null],
    },
    shadow: true,
    topLevel: false,
  },
  "fVmso.joua4IgCvob-yY": {
    opcode: "control_if",
    next: "bpC.}8WJidWgeo#k#6j3",
    parent: "|}#t;snIZ/StTVPDkol+",
    inputs: {
      CONDITION: [2, "!vr3KA7F{O@eeuI~n/c!"],
      SUBSTACK: [2, "twC-LC+p=8yX[CVzmnFP"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "!vr3KA7F{O@eeuI~n/c!": {
    opcode: "operator_not",
    next: null,
    parent: "fVmso.joua4IgCvob-yY",
    inputs: {
      OPERAND: [2, "}yQp+M,NP+m4@moTa.5h"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "}yQp+M,NP+m4@moTa.5h": {
    opcode: "operator_equals",
    next: null,
    parent: "!vr3KA7F{O@eeuI~n/c!",
    inputs: {
      OPERAND1: [3, "y5afiFl(0I7Q1^#yAc9.", [10, ""]],
      OPERAND2: [3, ".`/uav.j!.)Wm#2Z66eX", [10, "50"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "y5afiFl(0I7Q1^#yAc9.": {
    opcode: "looks_costumenumbername",
    next: null,
    parent: "}yQp+M,NP+m4@moTa.5h",
    inputs: {},
    fields: {
      NUMBER_NAME: ["name", null],
    },
    shadow: false,
    topLevel: false,
  },
  ".`/uav.j!.)Wm#2Z66eX": {
    opcode: "operator_letter_of",
    next: null,
    parent: "}yQp+M,NP+m4@moTa.5h",
    inputs: {
      LETTER: [3, [12, "i", "display_index"], [6, "1"]],
      STRING: [3, "_9Xkr}xNn6Ss6G1u;Su]", [10, "😭"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "_9Xkr}xNn6Ss6G1u;Su]": {
    opcode: "argument_reporter_string_number",
    next: null,
    parent: ".`/uav.j!.)Wm#2Z66eX",
    inputs: {},
    fields: {
      VALUE: ["text", null],
    },
    shadow: false,
    topLevel: false,
  },
  "twC-LC+p=8yX[CVzmnFP": {
    opcode: "looks_switchcostumeto",
    next: null,
    parent: "fVmso.joua4IgCvob-yY",
    inputs: {
      COSTUME: [1, "]|c,#b-wINwA}:=o4o)f"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "]|c,#b-wINwA}:=o4o)f": {
    opcode: "looks_costume",
    next: null,
    parent: "twC-LC+p=8yX[CVzmnFP",
    inputs: {},
    fields: {
      COSTUME: ["undefined", null],
    },
    shadow: true,
    topLevel: false,
  },
  "bpC.}8WJidWgeo#k#6j3": {
    opcode: "control_create_clone_of",
    next: "-7s#8Xb{vbkZ_aE-8Y?1",
    parent: "fVmso.joua4IgCvob-yY",
    inputs: {
      CLONE_OPTION: [1, ";@aw-5w;@)OSWc^`#6^1"],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  ";@aw-5w;@)OSWc^`#6^1": {
    opcode: "control_create_clone_of_menu",
    next: null,
    parent: "bpC.}8WJidWgeo#k#6j3",
    inputs: {},
    fields: {
      CLONE_OPTION: ["_myself_", null],
    },
    shadow: true,
    topLevel: false,
  },
  "-7s#8Xb{vbkZ_aE-8Y?1": {
    opcode: "motion_movesteps",
    next: "bh0c18-i[v^N3nvby}ca",
    parent: "bpC.}8WJidWgeo#k#6j3",
    inputs: {
      STEPS: [3, "%Id*180^*v0NyFjvqA/?", [4, "10"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "%Id*180^*v0NyFjvqA/?": {
    opcode: "operator_multiply",
    next: null,
    parent: "-7s#8Xb{vbkZ_aE-8Y?1",
    inputs: {
      NUM1: [3, "C~Lj*Q3*_1jDGX)ijewB", [4, ""]],
      NUM2: [3, "S?_KL]^qbt{wr+*i(5ZF", [4, ""]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "C~Lj*Q3*_1jDGX)ijewB": {
    opcode: "operator_divide",
    next: null,
    parent: "%Id*180^*v0NyFjvqA/?",
    inputs: {
      NUM1: [3, "pFr71zwV[bfbK(Bp,er5", [4, ""]],
      NUM2: [1, [4, "100"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "pFr71zwV[bfbK(Bp,er5": {
    opcode: "looks_size",
    next: null,
    parent: "C~Lj*Q3*_1jDGX)ijewB",
    inputs: {},
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "S?_KL]^qbt{wr+*i(5ZF": {
    opcode: "data_itemoflist",
    next: null,
    parent: "%Id*180^*v0NyFjvqA/?",
    inputs: {
      INDEX: [3, "}QVD6rD(MAeSGxm_[)%M", [7, "1"]],
    },
    fields: {
      LIST: ["Advance Width", "advance_width"],
    },
    shadow: false,
    topLevel: false,
  },
  "}QVD6rD(MAeSGxm_[)%M": {
    opcode: "looks_costumenumbername",
    next: null,
    parent: "S?_KL]^qbt{wr+*i(5ZF",
    inputs: {},
    fields: {
      NUMBER_NAME: ["number", null],
    },
    shadow: false,
    topLevel: false,
  },
  "bh0c18-i[v^N3nvby}ca": {
    opcode: "data_changevariableby",
    next: null,
    parent: "-7s#8Xb{vbkZ_aE-8Y?1",
    inputs: {
      VALUE: [1, [4, "1"]],
    },
    fields: {
      VARIABLE: ["i", "display_index"],
    },
    shadow: false,
    topLevel: false,
  },
  "g7i[~Ts%_4+[a[qF6Xm[": {
    opcode: "looks_hide",
    next: null,
    parent: "=VO(cpH(vlYoit^~[zV)",
    inputs: {},
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "1GR0/df3!|K55(2,[B`e": {
    opcode: "event_whenflagclicked",
    next: "JAdUQ^:Bh6O}jd4O_R*I",
    parent: null,
    inputs: {},
    fields: {},
    shadow: false,
    topLevel: true,
    x: 0,
    y: 728,
  },
  "JAdUQ^:Bh6O}jd4O_R*I": {
    opcode: "looks_seteffectto",
    next: "_~rTB`?K:WvbtJF!6lM`",
    parent: "1GR0/df3!|K55(2,[B`e",
    inputs: {
      VALUE: [1, [4, "-100"]],
    },
    fields: {
      EFFECT: ["BRIGHTNESS", null],
    },
    shadow: false,
    topLevel: false,
  },
  "_~rTB`?K:WvbtJF!6lM`": {
    opcode: "motion_gotoxy",
    next: "P[5lgBx3;?;*a~c`D(hY",
    parent: "JAdUQ^:Bh6O}jd4O_R*I",
    inputs: {
      X: [1, [4, "0"]],
      Y: [1, [4, "0"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
  },
  "P[5lgBx3;?;*a~c`D(hY": {
    opcode: "procedures_call",
    next: null,
    parent: "_~rTB`?K:WvbtJF!6lM`",
    inputs: {
      "4PK./iHHj:gdrSiUlMi2": [1, [10, "Hello world!"]],
    },
    fields: {},
    shadow: false,
    topLevel: false,
    mutation: {
      tagName: "mutation",
      children: [],
      proccode: "Display %s",
      argumentids: '["4PK./iHHj:gdrSiUlMi2"]',
      warp: "true",
    },
  },
};
