/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "noTranslations": true,
  "name": "Custom palette scroll speed",
  "description": "Change the speed that the palette scrolls.",
  "tags": ["new"],
  "credits": [
    {
      "name": "LilyMakesThings",
      "link": "https://scratch.mit.edu/users/LilyMakesThings/"
    }
  ],
  "enabledByDefault": true,
  "userscripts": [
    {
      "url": "scroll.js"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "On Category Select",
      "id": "selectSpeed",
      "type": "select",
      "potentialValues": [
        {
          "id": "none",
          "name": "Instant"
        },
        {
          "id": "veryfast",
          "name": "Very Fast"
        },
        {
          "id": "fast",
          "name": "Fast"
        },
        {
          "id": "default",
          "name": "Default"
        },
        {
          "id": "long",
          "name": "Slow"
        }
      ],
      "default": "default",
    }
  ]
};
export default manifest;