name: Prettier

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: write

jobs:
  prettier:
    name: Format code
    runs-on: ubuntu-latest

    steps:
      # IMPORTANT:
      # Checkout the actual branch instead of leaving Git in
      # detached HEAD state.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      # Run ScratchAddons' Prettier action
      - name: Run Prettier
        uses: ScratchAddons/prettier_action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prettier_options: --write .
          prettier_version: 3.2.5
