name: Pack extensions
on:
  workflow_dispatch:
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Pack extensions for Firefox
        uses: ScratchAddons/packer-script@main
        env:
          ENVIRONMENT: firefox
      - name: Pack extensions for Chrome
        uses: ScratchAddons/packer-script@main
        env:
          ENVIRONMENT: chrome
      - name: Upload packed extensions
        uses: actions/upload-artifact@v4
        with:
          name: Packed Extensions (zip)
          path: dist/*.zip
