name: Send comment on stale issues
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ScratchAddons'
    steps:
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Execute Action
        uses: actions/stale@v6
        with:
          stale-issue-message: 'Ping! There has been no activity for 7 days.'
          stale-pr-message: 'Ping! There has been no activity for 7 days.'
          only-labels: 'status: awaiting answer/followup'
          days-before-stale: 7
          days-before-close: -1
          stale-issue-label: 'status: stale'
          stale-pr-label: 'status: stale'
          operations-per-run: 30
          repo-token: ${{ steps.generate-token.outputs.token }}
