name: Sync strings with Transifex
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * Sun"
jobs:
  transifex:
    name: Transifex
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ScratchAddons'
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26.x
      - name: Generate token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Push and pull strings
        uses: ScratchAddons/l10n-script@main
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
