name: Unittest
on:
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ScratchAddons'
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Run unittest
        uses: ScratchAddons/meow@main
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
