name: Unittest
on:
  workflow_dispatch:
jobs:
  unittest:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ScratchAddons'
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26.x
      - name: Generate token
        uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Run unittest
        uses: ScratchAddons/meow@main
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
